version: "3.7"

services:
  web:
    image: php:7.3-apache
    depends_on:
      - mariadb
    ports:
      - 80:80
    volumes:
      - "./DocumentRoot:/var/www/html"
      - mariadb-volume:/var/lib/mysql
    links:
      - mariadb
  mariadb:
    image: mariadb:10.5.2
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: "testuser"
      MYSQL_PASSWORD: "testpassword"
      MYSQL_DATABASE: "wordpress"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - "mariadb:db"
    ports:
      - 8081:80
volumes:
  mariadb-volume:
