version: "3.7"
services:
  server:
    container_name: server
    depends_on:
      - mongo
    environment:
      MONGODB_ROOT: ${MONGODB_ROOT}
      MONGODB_PASSWD: ${MONGODB_PASSWD}
      MONGO_PORT: ${MONGO_PORT}
      MONGODB_INITDB: ${MONGODB_INITDB}
      MONGODB_HOST: ${MONGODB_HOST}
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server/app.js:/usr/app/app.js
    networks:
      master:
        aliases:
          - server
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWD}
      MONGO_INITDB_NAME: ${MONGODB_INITDB}
    volumes:
      - ./mongo/mongod.log:/var/log/mongodb/mongod.log
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/dbscript.js:/docker-entrypoint-initdb.d/dbscript.js
      - ./mongo/data:/data/db
    networks:
      master:
        aliases:
          - mongo
networks:
  master:
    external: true